import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  { href: "/", label: "Inicio" },
  { href: "/elliott-full-cycle", label: "Ciclo 5+ABC" },
  { href: "/elliott-superposition", label: "Superposición" },
  { href: "/miner-dual-tf-system", label: "Dual TF" },
  { href: "/fibonacci-dummies", label: "Fibonacci" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="sticky top-0 z-50 border-b border-white/10 bg-[#050912]/80 backdrop-blur">
          <div className="mx-auto flex w-full max-w-6xl items-center justify-between px-6 py-3">
            <Link href="/" className="flex items-center gap-2 text-xs font-semibold tracking-[0.3em] text-[#7fb2ff]">
              MONER LAB
            </Link>
            <div className="hidden items-center gap-2 text-xs font-semibold text-[#9fb3cf] md:flex">
              {navLinks.map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  className="rounded-full border border-transparent px-3 py-2 transition hover:border-[#2a3f6a] hover:bg-[#0b1426] hover:text-white"
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
